### ISSUE TITLE
Invalid regex when using double stars

### ISSUE THREAD

**Issue by jairbubbles** [goelhardik/ignore#22]
`**foo.txt` will produce `**foo\.txt(/.*)?$` which is not valid:

```
System.Text.RegularExpressions.RegexParseException
Invalid pattern '**foo\.txt(/.*)?$' at offset 1. Quantifier {x,y} following nothing.
```

**Comment by jairbubbles** [comment]
Looks like my fix it not enough, I'm seeing issues with other rules.

Here is a glimpse:

```
/**/lunr-index.json
/**/*_generated.csproj
```

**Comment by goelhardik** [comment]
Reopening to look at these again.

**Comment by goelhardik** [comment]
I can take a look probably tomorrow.

**Comment by goelhardik** [comment]
It's weird there is no documentation about this kind of case `private/**.ps`. I can see it ignores files like `private/aa.ps`, thus behaving the same as `private/*.ps`. Not sure if it's supposed to catch any other cases.

**Comment by goelhardik** [comment]
Still pending:

```
private/**.ps
```

**Comment by jairbubbles** [comment]
In fact I took the example from a Perforce repository which has similar ignore rules like git. It's not very documented so I'm not sure it's exactly the same behavior.

I feel like we should just make sure it doesn't throw when parsing the rule.
