### ISSUE TITLE
Dotfiles are not handled correctly

### ISSUE THREAD

**Issue by JKamsker** [goelhardik/ignore#40]
```csharp
var ignore = new Ignore.Ignore();
ignore.Add(".*");

ignore.IsIgnored("/.dotfile").Dump(); // returns true
ignore.IsIgnored("/no.dotfile").Dump(); // returns true
```

The second one should not be ignored.

Tested using git.
Gitignore:
```
.*
```
Created the files ``.dotfile`` and ``no.dotfile``: ``no.dotfile`` shows up in the ``changes`` tab.

**Comment by goelhardik** [comment]
@JKamsker thanks for submitting the test PR. The version >= 0.1.50 should have the bug fix.
