### ISSUE TITLE
Library inclusion: `using Ignore;` Not working

### ISSUE THREAD

**Issue by usmanmehmood55** [goelhardik/ignore#54]
I added the library using the nuGet manager and I tried to include it in my app like this:

```cs
using Ignore; // <- This is greyed out
namespace SomeNamespace
{
    internal class Program
    {
        var ignoreList = new Ignore(); // <- error: 'Ignore' is a namespace but is used like a type
    }
}
```

When I use it like `new Ignore.Ignore` it works. It just looks ugly.

```cs
// removed `using Ignore;`
namespace SomeNamespace
{
    internal class Program
    {
        var ignoreList = new Ignore.Ignore(); // <- Now it works
    }
}
```

**Comment by goelhardik** [comment]
I don't think this can be avoided unless we change the namespace.

You could define an alias for the class like `using MyClass = Ignore.Ignore` and then do `new MyClass()` later.

**Comment by usmanmehmood55** [comment]
@goelhardik I think it would be an overall cleaner solution if the namespace was changed. The alias thing works but it looks strange.
